### ISSUE TITLE
Is died?

### ISSUE THREAD

**Issue by gpaixao** [raphamorim/write-code-every-day#214]
This project died?

**Comment by ceasbz** [comment]
@gpaixao No, but the link changed to: http://raphamorim.io/write-code-every-day/

**Comment by gpaixao** [comment]
I changed my username, already did send PR with my new username. Can you help me, accepting?

**Comment by gpaixao** [comment]
Tks @ceasbz

**Comment by ceasbz** [comment]
@gpaixao I'm not a collaborator of project, only @raphamorim can accept.

**Comment by gpaixao** [comment]
Fail when writing username :face_with_head_bandage:

**Comment by raphamorim** [comment]
Sorry guys, merged

**Comment by raphamorim** [comment]
I looking for a new mantainer for this project btw.

**Comment by gpaixao** [comment]
@raphamorim create an organization and include members...

**Comment by raphamorim** [comment]
For only one project doesn't make sense.
More easy give permission for this one.

**Comment by gpaixao** [comment]
right!
