### ISSUE TITLE
What is missing to complete?

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/write-code-every-day#3]
- [x] Domain
- [x] Open Graph for facebook share
- [x] A file `about.md` telling about the chellenge and how script works

**Comment by raphamorim** [comment]
url add to google

**Comment by rafaelfragosom** [comment]
I updated the `about.md` with the right grammar and fixed some of the typos.

**Comment by BrunoKinoshita** [comment]
Added a Licence (MIT)

**Comment by raphamorim** [comment]
@afonsopacifer can you see this missing itens later?

**Comment by afonsopacifer** [comment]
@raphamorim, of course, 
maybe today, I send the PR :)

**Comment by afonsopacifer** [comment]
@willianjusten completed the issue and more :)  
#35
