### ISSUE TITLE
Find a better way to calculate the longest streak

### ISSUE THREAD

**Issue by alanrsoares** [raphamorim/write-code-every-day#30]
Values being displayed for some users do not match the actual numbers on Github.
The values should be built in a reliable environment.

**Comment by viniciusdacal** [comment]
Yah, I notice that too. 
I think it's getting our currentStreak instead the longestStreak.

**Comment by raphamorim** [comment]
Yeah, I searching for others ways too. 

Today the script takes rather longest streak only if are your currently longest streak. 
'Cause **Github API doesn't provide the longest streak**, so I have to get this data manually (worst option ever).

What problems it generates?

1 - If you already spend 365 days and stopping the other. It simply does not credit the contributions.
2 - I need to run the build script to 00: 00h every day. (to create an automation)

I'm open to suggestions :)

**Comment by rafaelfragosom** [comment]
Github makes it more complicated than it should actually be. 

Maybe we could setup a background job to pull the contributions of the previous day and make our own database? We can reset the counter if a person forgets to contribute.

-----------------------

P.S.: The home page is getting too long, it's getting massive. Maybe we could only do a top 10 and a 'view all' page with pagination?

**Comment by alanrsoares** [comment]
Sounds like a plan. Fairly easy to get done I'd say.

**Comment by alanrsoares** [comment]
As for the massive growth the page is having, I'd probably go for a
highlight size of the top ten, then following a thumbnail view for the next
20.

**Comment by viniciusdacal** [comment]
For now, I think we could change the label 'Longest streak' to 'Current streak'. What do you think guys?

**Comment by vitorleal** [comment]
What if we use the SVG graphs that GitHub generate (like this one https://github.com/users/vitorleal/contributions) and make a script to count **longest streak**. Then we put a cronjob to run it midnight every day.

Cheers!

**Comment by raphamorim** [comment]
The cronjob will roll, I will put to this current build script. But the problem with the solution of SVG: Maximum days of contributions will always be 365 days

**Comment by raphamorim** [comment]
I'm thinking the solution with db. But I do not like too use a database to solve this problem. So I opted file, since it generates static.

**Comment by raphamorim** [comment]
Currently this script works well for what is proposed, considering that it scans only the starting current streak. The problem is that it is too costly.

BTW: He's not current, it takes the longest current according to the user signed up for challenge. If you stop the challenge, this data is saved in a file share and does not change until it surpass that mark.

This is the case of [@israelst](http://github.com/israelst)

**Comment by raphamorim** [comment]
See the line 16, to see what I'm talking about: https://github.com/raphamorim/write-code-every-day/blob/master/src/contributors.build.js

**Comment by raphamorim** [comment]
But as I said, it is costly and heavy. Because have multiple requests and still spend a lot memory

**Comment by rafaelfragosom** [comment]
Background Jobs and caching, no need to use DB for now.

**Comment by gpedro** [comment]
I made a small service to pick up this github information: https://github.com/gpedro/github-streak

> http://github-streak.herokuapp.com/gpedro
we can create a json with usernames to crawl streak and update the website ._.

**Comment by alanrsoares** [comment]
Seems to be working fine, good job mate!

**Comment by leaofelipe** [comment]
What about use something like __CURL__ and get the information directly from the user page?

**Comment by raphamorim** [comment]
Guys, forget this issue, I removed the longstreak.

Reference: #82
