### ISSUE TITLE
A better sort 

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/write-code-every-day#82]
Talking to a friend, it became clear that is looking like the write code is like a competition of who have more longest streak. I suggest then sort the developers based on another parameter.

As it's a manifesto, i think may be best to order the order that was added in challenge.

**Comment by raphamorim** [comment]
Reference: d9a4ce93de6a39e2ef7b3d4036e04e38a6c5095f

**Comment by raphamorim** [comment]
However I still wanna show info about developers

**Comment by rodrigopinto** [comment]
A random sort would solve any competition feeling.

**Comment by rafaelfragosom** [comment]
+1 for @rodrigopinto

**Comment by raphamorim** [comment]
Yeah, I was doing it.

But I'm short on time because of BrazilJS. If you can do, please make make a PR :)

**Comment by rafaelfragosom** [comment]
I think we should remove the streak and sort the developers every time the page loads.

FYI: It doesn't make sense to compete in something that counts everyday. But anyways, a competition won't harm either, as long as they contribute with valuable code everyday. Though decision.

**Comment by rafaelfragosom** [comment]
See #97
