### ISSUE TITLE
Let's back to show the longest streak?

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/write-code-every-day#98]
With random sort I think the problems listed in #82 has been solved

**Comment by afonsopacifer** [comment]
I think useful

**Comment by henriquebelfort** [comment]
Is there some impediment?

**Comment by raphamorim** [comment]
Nopes, I'll start this feature next week.

**Comment by rafaelfragosom** [comment]
@raphamorim create the PR for this feature, I want to add something. I'm extracting the DOM shuffler I wrote and adding to NPM.
